.class public final Lcom/google/android/gms/common/server/o;
.super Ljava/lang/Object;
.source "SourceFile"


# direct methods
.method public static a(Landroid/content/Context;Lcom/google/android/gms/common/server/p;)V
    .locals 4

    .prologue
    const/4 v3, 0x5

    .line 152
    iget-object v0, p1, Lcom/google/android/gms/common/server/p;->a:Landroid/content/Intent;

    const-string v1, "accountName"

    invoke-virtual {v0, v1}, Landroid/content/Intent;->getStringExtra(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v0

    invoke-static {v0}, Lcom/google/android/gms/common/internal/aj;->a(Ljava/lang/Object;)Ljava/lang/Object;

    iget-object v0, p1, Lcom/google/android/gms/common/server/p;->a:Landroid/content/Intent;

    const-string v1, "startView"

    invoke-virtual {v0, v1}, Landroid/content/Intent;->getParcelableExtra(Ljava/lang/String;)Landroid/os/Parcelable;

    move-result-object v0

    check-cast v0, Lcom/google/android/gms/common/server/FavaDiagnosticsEntity;

    invoke-static {v0}, Lcom/google/android/gms/common/internal/aj;->a(Ljava/lang/Object;)Ljava/lang/Object;

    invoke-virtual {p1}, Lcom/google/android/gms/common/server/p;->b()Lcom/google/android/gms/common/server/FavaDiagnosticsEntity;

    move-result-object v0

    if-nez v0, :cond_2

    invoke-virtual {p1}, Lcom/google/android/gms/common/server/p;->a()Lcom/google/android/gms/common/server/FavaDiagnosticsEntity;

    move-result-object v0

    invoke-static {v0}, Lcom/google/android/gms/common/internal/aj;->a(Ljava/lang/Object;)Ljava/lang/Object;

    :cond_0
    :goto_0
    iget-object v0, p1, Lcom/google/android/gms/common/server/p;->a:Landroid/content/Intent;

    .line 153
    invoke-virtual {p0}, Landroid/content/Context;->getPackageManager()Landroid/content/pm/PackageManager;

    move-result-object v1

    const/4 v2, 0x0

    invoke-virtual {v1, v0, v2}, Landroid/content/pm/PackageManager;->queryIntentServices(Landroid/content/Intent;I)Ljava/util/List;

    move-result-object v1

    invoke-interface {v1}, Ljava/util/List;->isEmpty()Z

    move-result v1

    if-nez v1, :cond_4

    .line 154
    invoke-static {}, Landroid/app/ActivityManager;->isUserAMonkey()Z

    move-result v1

    if-eqz v1, :cond_3

    .line 158
    const-string v0, "PlusAnalytics"

    invoke-static {v0, v3}, Landroid/util/Log;->isLoggable(Ljava/lang/String;I)Z

    move-result v0

    if-eqz v0, :cond_1

    .line 159
    const-string v0, "PlusAnalytics"

    const-string v1, "Unable to log events generated by the monkey test runner."

    invoke-static {v0, v1}, Landroid/util/Log;->w(Ljava/lang/String;Ljava/lang/String;)I

    .line 167
    :cond_1
    :goto_1
    return-void

    .line 152
    :cond_2
    invoke-virtual {p1}, Lcom/google/android/gms/common/server/p;->a()Lcom/google/android/gms/common/server/FavaDiagnosticsEntity;

    move-result-object v0

    if-nez v0, :cond_0

    invoke-virtual {p1}, Lcom/google/android/gms/common/server/p;->b()Lcom/google/android/gms/common/server/FavaDiagnosticsEntity;

    move-result-object v0

    invoke-static {v0}, Lcom/google/android/gms/common/internal/aj;->a(Ljava/lang/Object;)Ljava/lang/Object;

    goto :goto_0

    .line 163
    :cond_3
    invoke-virtual {p0, v0}, Landroid/content/Context;->startService(Landroid/content/Intent;)Landroid/content/ComponentName;

    goto :goto_1

    .line 164
    :cond_4
    const-string v1, "PlusAnalytics"

    invoke-static {v1, v3}, Landroid/util/Log;->isLoggable(Ljava/lang/String;I)Z

    move-result v1

    if-eqz v1, :cond_1

    .line 165
    const-string v1, "PlusAnalytics"

    new-instance v2, Ljava/lang/StringBuilder;

    const-string v3, "Unable to log plus action: "

    invoke-direct {v2, v3}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V

    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    move-result-object v0

    invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    invoke-static {v1, v0}, Landroid/util/Log;->w(Ljava/lang/String;Ljava/lang/String;)I

    goto :goto_1
.end method

.method public static a(Landroid/content/Context;Ljava/lang/String;Lcom/google/android/gms/common/server/FavaDiagnosticsEntity;Lcom/google/android/gms/common/server/FavaDiagnosticsEntity;Ljava/lang/String;)V
    .locals 9

    .prologue
    const/4 v2, 0x0

    .line 47
    move-object v0, p0

    move-object v1, p1

    move-object v3, p2

    move-object v4, p3

    move-object v5, p4

    move-object v6, v2

    move-object v7, v2

    move-object v8, v2

    invoke-static/range {v0 .. v8}, Lcom/google/android/gms/common/server/o;->a(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Lcom/google/android/gms/common/server/FavaDiagnosticsEntity;Lcom/google/android/gms/common/server/FavaDiagnosticsEntity;Ljava/lang/String;Ljava/util/ArrayList;Ljava/lang/Boolean;Ljava/lang/Boolean;)V

    .line 49
    return-void
.end method

.method public static a(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Lcom/google/android/gms/common/server/FavaDiagnosticsEntity;Lcom/google/android/gms/common/server/FavaDiagnosticsEntity;Ljava/lang/String;Ljava/util/ArrayList;Ljava/lang/Boolean;Ljava/lang/Boolean;)V
    .locals 9

    .prologue
    .line 86
    if-eqz p8, :cond_2

    invoke-virtual/range {p8 .. p8}, Ljava/lang/Boolean;->booleanValue()Z

    move-result v0

    if-eqz v0, :cond_2

    const/4 v0, 0x1

    :goto_0
    invoke-static {v0}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    move-result-object v0

    .line 87
    if-eqz p6, :cond_13

    if-eqz p7, :cond_13

    invoke-virtual/range {p7 .. p7}, Ljava/lang/Boolean;->booleanValue()Z

    move-result v1

    invoke-virtual {v0}, Ljava/lang/Boolean;->booleanValue()Z

    move-result v0

    new-instance v2, Ljava/util/ArrayList;

    invoke-direct {v2}, Ljava/util/ArrayList;-><init>()V

    if-eqz v0, :cond_0

    const-string v0, "6"

    invoke-virtual {v2, v0}, Ljava/util/ArrayList;->add(Ljava/lang/Object;)Z

    :cond_0
    if-eqz v1, :cond_3

    const-string v0, "5"

    invoke-virtual {v2, v0}, Ljava/util/ArrayList;->add(Ljava/lang/Object;)Z

    new-instance v0, Lcom/google/android/gms/plus/service/v1whitelisted/models/bj;

    invoke-direct {v0}, Lcom/google/android/gms/plus/service/v1whitelisted/models/bj;-><init>()V

    new-instance v1, Lcom/google/android/gms/plus/service/v1whitelisted/models/bg;

    invoke-direct {v1}, Lcom/google/android/gms/plus/service/v1whitelisted/models/bg;-><init>()V

    invoke-virtual {v1, v2}, Lcom/google/android/gms/plus/service/v1whitelisted/models/bg;->a(Ljava/util/List;)Lcom/google/android/gms/plus/service/v1whitelisted/models/bg;

    move-result-object v1

    invoke-virtual {v1}, Lcom/google/android/gms/plus/service/v1whitelisted/models/bg;->a()Lcom/google/android/gms/plus/service/v1whitelisted/models/bf;

    move-result-object v1

    invoke-virtual {v0, v1}, Lcom/google/android/gms/plus/service/v1whitelisted/models/bj;->a(Lcom/google/android/gms/plus/service/v1whitelisted/models/bf;)Lcom/google/android/gms/plus/service/v1whitelisted/models/bj;

    move-result-object v0

    invoke-virtual {v0}, Lcom/google/android/gms/plus/service/v1whitelisted/models/bj;->a()Lcom/google/android/gms/plus/service/v1whitelisted/models/bi;

    move-result-object v0

    check-cast v0, Lcom/google/android/gms/plus/service/v1whitelisted/models/ClientActionDataEntity;

    :goto_1
    if-eqz p0, :cond_1

    invoke-virtual {p0}, Landroid/content/Context;->getPackageName()Ljava/lang/String;

    move-result-object v1

    if-nez v1, :cond_14

    :cond_1
    const-string v0, "PlusAnalytics"

    const-string v1, "Package name for the given context is null. Unable to log given action."

    invoke-static {v0, v1}, Landroid/util/Log;->e(Ljava/lang/String;Ljava/lang/String;)I

    .line 91
    :goto_2
    return-void

    .line 86
    :cond_2
    const/4 v0, 0x0

    goto :goto_0

    .line 87
    :cond_3
    if-eqz p6, :cond_13

    new-instance v3, Ljava/util/ArrayList;

    invoke-direct {v3}, Ljava/util/ArrayList;-><init>()V

    new-instance v4, Ljava/util/ArrayList;

    invoke-direct {v4}, Ljava/util/ArrayList;-><init>()V

    invoke-interface {p6}, Ljava/util/List;->size()I

    move-result v5

    const/4 v0, 0x0

    move v1, v0

    :goto_3
    if-ge v1, v5, :cond_d

    invoke-interface {p6, v1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lcom/google/android/gms/common/people/data/AudienceMember;

    if-eqz v0, :cond_4

    invoke-virtual {v0}, Lcom/google/android/gms/common/people/data/AudienceMember;->h()Z

    move-result v6

    if-eqz v6, :cond_5

    invoke-virtual {v0}, Lcom/google/android/gms/common/people/data/AudienceMember;->d()Ljava/lang/String;

    move-result-object v0

    new-instance v6, Lcom/google/android/gms/plus/service/v1whitelisted/models/bm;

    invoke-direct {v6}, Lcom/google/android/gms/plus/service/v1whitelisted/models/bm;-><init>()V

    iput-object v0, v6, Lcom/google/android/gms/plus/service/v1whitelisted/models/bm;->a:Ljava/lang/String;

    iget-object v0, v6, Lcom/google/android/gms/plus/service/v1whitelisted/models/bm;->b:Ljava/util/Set;

    const/4 v7, 0x2

    invoke-static {v7}, Ljava/lang/Integer;->valueOf(I)Ljava/lang/Integer;

    move-result-object v7

    invoke-interface {v0, v7}, Ljava/util/Set;->add(Ljava/lang/Object;)Z

    new-instance v0, Lcom/google/android/gms/plus/service/v1whitelisted/models/ClientLoggedCircleEntity;

    iget-object v7, v6, Lcom/google/android/gms/plus/service/v1whitelisted/models/bm;->b:Ljava/util/Set;

    iget-object v6, v6, Lcom/google/android/gms/plus/service/v1whitelisted/models/bm;->a:Ljava/lang/String;

    invoke-direct {v0, v7, v6}, Lcom/google/android/gms/plus/service/v1whitelisted/models/ClientLoggedCircleEntity;-><init>(Ljava/util/Set;Ljava/lang/String;)V

    invoke-virtual {v3, v0}, Ljava/util/ArrayList;->add(Ljava/lang/Object;)Z

    :cond_4
    :goto_4
    add-int/lit8 v0, v1, 0x1

    move v1, v0

    goto :goto_3

    :cond_5
    invoke-virtual {v0}, Lcom/google/android/gms/common/people/data/AudienceMember;->j()Z

    move-result v6

    if-eqz v6, :cond_a

    invoke-virtual {v0}, Lcom/google/android/gms/common/people/data/AudienceMember;->e()Ljava/lang/String;

    move-result-object v0

    invoke-static {v0}, Lcom/google/android/gms/people/internal/t;->a(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v6

    invoke-static {v0}, Lcom/google/android/gms/people/internal/t;->c(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v7

    invoke-static {v6}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z

    move-result v8

    if-eqz v8, :cond_7

    invoke-static {v7}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z

    move-result v8

    if-eqz v8, :cond_7

    const-string v6, "AclDetails"

    const/4 v7, 0x5

    invoke-static {v6, v7}, Landroid/util/Log;->isLoggable(Ljava/lang/String;I)Z

    move-result v6

    if-eqz v6, :cond_6

    const-string v6, "AclDetails"

    new-instance v7, Ljava/lang/StringBuilder;

    const-string v8, "unhandled people qualified ID: "

    invoke-direct {v7, v8}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V

    invoke-virtual {v7, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    invoke-static {v6, v0}, Landroid/util/Log;->w(Ljava/lang/String;Ljava/lang/String;)I

    :cond_6
    const/4 v0, 0x0

    :goto_5
    if-eqz v0, :cond_4

    invoke-virtual {v4, v0}, Ljava/util/ArrayList;->add(Ljava/lang/Object;)Z

    goto :goto_4

    :cond_7
    new-instance v8, Lcom/google/android/gms/plus/service/v1whitelisted/models/bp;

    invoke-direct {v8}, Lcom/google/android/gms/plus/service/v1whitelisted/models/bp;-><init>()V

    invoke-static {v6}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z

    move-result v0

    if-nez v0, :cond_8

    iput-object v6, v8, Lcom/google/android/gms/plus/service/v1whitelisted/models/bp;->b:Ljava/lang/String;

    iget-object v0, v8, Lcom/google/android/gms/plus/service/v1whitelisted/models/bp;->c:Ljava/util/Set;

    const/4 v6, 0x5

    invoke-static {v6}, Ljava/lang/Integer;->valueOf(I)Ljava/lang/Integer;

    move-result-object v6

    invoke-interface {v0, v6}, Ljava/util/Set;->add(Ljava/lang/Object;)Z

    :cond_8
    invoke-static {v7}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z

    move-result v0

    if-nez v0, :cond_9

    iput-object v7, v8, Lcom/google/android/gms/plus/service/v1whitelisted/models/bp;->a:Ljava/lang/String;

    iget-object v0, v8, Lcom/google/android/gms/plus/service/v1whitelisted/models/bp;->c:Ljava/util/Set;

    const/4 v6, 0x3

    invoke-static {v6}, Ljava/lang/Integer;->valueOf(I)Ljava/lang/Integer;

    move-result-object v6

    invoke-interface {v0, v6}, Ljava/util/Set;->add(Ljava/lang/Object;)Z

    :cond_9
    new-instance v0, Lcom/google/android/gms/plus/service/v1whitelisted/models/ClientLoggedCircleMemberEntity;

    iget-object v6, v8, Lcom/google/android/gms/plus/service/v1whitelisted/models/bp;->c:Ljava/util/Set;

    iget-object v7, v8, Lcom/google/android/gms/plus/service/v1whitelisted/models/bp;->a:Ljava/lang/String;

    iget-object v8, v8, Lcom/google/android/gms/plus/service/v1whitelisted/models/bp;->b:Ljava/lang/String;

    invoke-direct {v0, v6, v7, v8}, Lcom/google/android/gms/plus/service/v1whitelisted/models/ClientLoggedCircleMemberEntity;-><init>(Ljava/util/Set;Ljava/lang/String;Ljava/lang/String;)V

    goto :goto_5

    :cond_a
    invoke-virtual {v0}, Lcom/google/android/gms/common/people/data/AudienceMember;->i()Z

    move-result v6

    if-eqz v6, :cond_c

    invoke-virtual {v0}, Lcom/google/android/gms/common/people/data/AudienceMember;->c()I

    move-result v6

    packed-switch v6, :pswitch_data_0

    const-string v6, "AclDetails"

    const/4 v7, 0x5

    invoke-static {v6, v7}, Landroid/util/Log;->isLoggable(Ljava/lang/String;I)Z

    move-result v6

    if-eqz v6, :cond_b

    const-string v6, "AclDetails"

    new-instance v7, Ljava/lang/StringBuilder;

    const-string v8, "unhandled PeopleConstants.CircleType: "

    invoke-direct {v7, v8}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V

    invoke-virtual {v0}, Lcom/google/android/gms/common/people/data/AudienceMember;->c()I

    move-result v0

    invoke-virtual {v7, v0}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;

    move-result-object v0

    invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    invoke-static {v6, v0}, Landroid/util/Log;->w(Ljava/lang/String;Ljava/lang/String;)I

    :cond_b
    const-string v0, "0"

    :goto_6
    invoke-virtual {v2, v0}, Ljava/util/ArrayList;->add(Ljava/lang/Object;)Z

    goto/16 :goto_4

    :pswitch_0
    const-string v0, "1"

    goto :goto_6

    :pswitch_1
    const-string v0, "2"

    goto :goto_6

    :pswitch_2
    const-string v0, "4"

    goto :goto_6

    :pswitch_3
    const-string v0, "3"

    goto :goto_6

    :cond_c
    const-string v6, "AclDetails"

    const/4 v7, 0x5

    invoke-static {v6, v7}, Landroid/util/Log;->isLoggable(Ljava/lang/String;I)Z

    move-result v6

    if-eqz v6, :cond_4

    const-string v6, "AclDetails"

    new-instance v7, Ljava/lang/StringBuilder;

    const-string v8, "unhandled AudienceMember type: "

    invoke-direct {v7, v8}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V

    invoke-virtual {v0}, Lcom/google/android/gms/common/people/data/AudienceMember;->b()I

    move-result v0

    invoke-virtual {v7, v0}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;

    move-result-object v0

    invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    invoke-static {v6, v0}, Landroid/util/Log;->w(Ljava/lang/String;Ljava/lang/String;)I

    goto/16 :goto_4

    :cond_d
    invoke-virtual {v3}, Ljava/util/ArrayList;->isEmpty()Z

    move-result v0

    if-eqz v0, :cond_f

    invoke-virtual {v4}, Ljava/util/ArrayList;->isEmpty()Z

    move-result v0

    if-eqz v0, :cond_f

    invoke-virtual {v2}, Ljava/util/ArrayList;->isEmpty()Z

    move-result v0

    if-eqz v0, :cond_f

    const-string v0, "AclDetails"

    const/4 v1, 0x5

    invoke-static {v0, v1}, Landroid/util/Log;->isLoggable(Ljava/lang/String;I)Z

    move-result v0

    if-eqz v0, :cond_e

    const-string v0, "AclDetails"

    new-instance v1, Ljava/lang/StringBuilder;

    const-string v2, "no AclDetails from audience: "

    invoke-direct {v1, v2}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V

    invoke-virtual {v1, p6}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    move-result-object v1

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    invoke-static {v0, v1}, Landroid/util/Log;->w(Ljava/lang/String;Ljava/lang/String;)I

    :cond_e
    const/4 v0, 0x0

    goto/16 :goto_1

    :cond_f
    new-instance v0, Lcom/google/android/gms/plus/service/v1whitelisted/models/bg;

    invoke-direct {v0}, Lcom/google/android/gms/plus/service/v1whitelisted/models/bg;-><init>()V

    invoke-virtual {v3}, Ljava/util/ArrayList;->isEmpty()Z

    move-result v1

    if-nez v1, :cond_10

    iput-object v3, v0, Lcom/google/android/gms/plus/service/v1whitelisted/models/bg;->a:Ljava/util/List;

    iget-object v1, v0, Lcom/google/android/gms/plus/service/v1whitelisted/models/bg;->c:Ljava/util/Set;

    const/4 v3, 0x2

    invoke-static {v3}, Ljava/lang/Integer;->valueOf(I)Ljava/lang/Integer;

    move-result-object v3

    invoke-interface {v1, v3}, Ljava/util/Set;->add(Ljava/lang/Object;)Z

    :cond_10
    invoke-virtual {v4}, Ljava/util/ArrayList;->isEmpty()Z

    move-result v1

    if-nez v1, :cond_11

    iput-object v4, v0, Lcom/google/android/gms/plus/service/v1whitelisted/models/bg;->b:Ljava/util/List;

    iget-object v1, v0, Lcom/google/android/gms/plus/service/v1whitelisted/models/bg;->c:Ljava/util/Set;

    const/4 v3, 0x4

    invoke-static {v3}, Ljava/lang/Integer;->valueOf(I)Ljava/lang/Integer;

    move-result-object v3

    invoke-interface {v1, v3}, Ljava/util/Set;->add(Ljava/lang/Object;)Z

    :cond_11
    invoke-virtual {v2}, Ljava/util/ArrayList;->isEmpty()Z

    move-result v1

    if-nez v1, :cond_12

    invoke-virtual {v0, v2}, Lcom/google/android/gms/plus/service/v1whitelisted/models/bg;->a(Ljava/util/List;)Lcom/google/android/gms/plus/service/v1whitelisted/models/bg;

    :cond_12
    new-instance v1, Lcom/google/android/gms/plus/service/v1whitelisted/models/bj;

    invoke-direct {v1}, Lcom/google/android/gms/plus/service/v1whitelisted/models/bj;-><init>()V

    invoke-virtual {v0}, Lcom/google/android/gms/plus/service/v1whitelisted/models/bg;->a()Lcom/google/android/gms/plus/service/v1whitelisted/models/bf;

    move-result-object v0

    invoke-virtual {v1, v0}, Lcom/google/android/gms/plus/service/v1whitelisted/models/bj;->a(Lcom/google/android/gms/plus/service/v1whitelisted/models/bf;)Lcom/google/android/gms/plus/service/v1whitelisted/models/bj;

    move-result-object v0

    invoke-virtual {v0}, Lcom/google/android/gms/plus/service/v1whitelisted/models/bj;->a()Lcom/google/android/gms/plus/service/v1whitelisted/models/bi;

    move-result-object v0

    check-cast v0, Lcom/google/android/gms/plus/service/v1whitelisted/models/ClientActionDataEntity;

    goto/16 :goto_1

    :cond_13
    const/4 v0, 0x0

    goto/16 :goto_1

    :cond_14
    new-instance v1, Lcom/google/android/gms/common/server/p;

    invoke-direct {v1, p0}, Lcom/google/android/gms/common/server/p;-><init>(Landroid/content/Context;)V

    invoke-virtual {v1, p1}, Lcom/google/android/gms/common/server/p;->b(Ljava/lang/String;)Lcom/google/android/gms/common/server/p;

    move-result-object v1

    iget-object v2, v1, Lcom/google/android/gms/common/server/p;->a:Landroid/content/Intent;

    const-string v3, "action"

    invoke-virtual {v2, v3, p3}, Landroid/content/Intent;->putExtra(Ljava/lang/String;Landroid/os/Parcelable;)Landroid/content/Intent;

    invoke-virtual {v1, p4}, Lcom/google/android/gms/common/server/p;->a(Lcom/google/android/gms/common/server/FavaDiagnosticsEntity;)Lcom/google/android/gms/common/server/p;

    move-result-object v1

    invoke-virtual {v1, p5}, Lcom/google/android/gms/common/server/p;->a(Ljava/lang/String;)Lcom/google/android/gms/common/server/p;

    move-result-object v1

    if-eqz v0, :cond_15

    iget-object v2, v1, Lcom/google/android/gms/common/server/p;->a:Landroid/content/Intent;

    const-string v3, "clientActionData"

    invoke-virtual {v2, v3, v0}, Landroid/content/Intent;->putExtra(Ljava/lang/String;Landroid/os/Parcelable;)Landroid/content/Intent;

    :cond_15
    invoke-static {p0, v1}, Lcom/google/android/gms/common/server/o;->a(Landroid/content/Context;Lcom/google/android/gms/common/server/p;)V

    goto/16 :goto_2

    :pswitch_data_0
    .packed-switch 0x1
        :pswitch_0
        :pswitch_1
        :pswitch_2
        :pswitch_3
    .end packed-switch
.end method
